Upgrade to go 1.15
giantswarm/prometheus-meta-operator pull request #107
Opened 2020-08-31 14:11 UTC by omegas27

2020-08-31 14:51 UTC, TheoBrigitte commented
I do not really see the point here, as this is still being built with go1.14.1

<img width="976" alt="image" src="https://user-images.githubusercontent.com/6536819/91733685-2d961680-ebaa-11ea-9a62-d628eee9590e.png">
https://app.circleci.com/pipelines/github/giantswarm/prometheus-meta-operator/526/workflows/58ab4706-2210-4a2b-b5b7-2adeb4d382ea/jobs/2269

2020-08-31 14:52 UTC, TheoBrigitte requested changes

2020-08-31 14:52 UTC, TheoBrigitte commented on CHANGELOG.md
> +- Upgrade to golang 1.15
I do not think this is worth a changelog entry.

2020-09-02 08:05 UTC, omegas27 commented
@TheoBrigitte I reverted to 1.14 and removed the changelog entry

2020-09-03 13:43 UTC, TheoBrigitte approved these changes

2020-09-03 13:49 UTC, merged